// Korean for every string the plugin shows; English is the key. Map names, player names and chat are never translated.
// `tests/ko.test.ts` fails on a `t("…")` or `msg("…")` in the source with no entry here, and on an entry nothing uses.
export const KO: Record<string, string> = {
  "A floating panel is dragged about and resized from its corner; a docked one sits in the right-hand column beside the map. The Dock and Float button in the panel does the same.": "떠 있는 패널은 끌어서 옮기고 모서리로 크기를 바꿉니다. 도킹한 패널은 맵 옆 오른쪽 열에 놓입니다. 패널의 도킹/띄우기 버튼도 같은 일을 합니다.",
  "A replay records the orders players gave, not what happened, so Aftermath shows what was asked for: buildings placed, where units were sent, build orders and actions per minute.": "리플레이는 실제로 일어난 일이 아니라 플레이어가 내린 명령을 기록합니다. 그래서 Aftermath는 요청된 것을 보여 줍니다: 지은 건물, 유닛을 보낸 곳, 빌드 오더, 분당 행동 수.",
  "A section claims more chunks than a replay can hold.": "한 섹션이 리플레이에 들어갈 수 있는 것보다 많은 조각을 가졌다고 합니다.",
  "A section claims to be larger than any replay.": "한 섹션이 어떤 리플레이보다도 크다고 합니다.",
  "A section holds more than its stated size.": "한 섹션에 적힌 크기보다 많은 데이터가 들어 있습니다.",
  "A section's data does not unpack.": "한 섹션의 데이터를 풀 수 없습니다.",
  "A section's size is missing.": "한 섹션의 크기가 없습니다.",
  "Actions per minute": "분당 행동 수",
  "Actions per minute over the game — click to go there": "게임 전체의 분당 행동 수 — 클릭하면 그 시점으로 갑니다",
  "Aftermath opens StarCraft replays, files ending in .rep.": "Aftermath는 .rep로 끝나는 StarCraft 리플레이 파일을 엽니다.",
  "All {n} replays of this map": "이 맵의 리플레이 {n}개 모두",
  "Build order": "빌드 오더",
  "Buildings": "건물",
  "Capture the Flag": "깃발 뺏기",
  "Chat": "채팅",
  "Close": "닫기",
  "Close this replay": "이 리플레이 닫기",
  "Could not read {name}": "{name}을(를) 읽을 수 없습니다",
  "Count the whole game rather than up to the timeline": "타임라인까지가 아니라 게임 전체를 셉니다",
  "Dock": "도킹",
  "Docked on the right": "오른쪽에 도킹",
  "Drop replays (.rep) here, or": "리플레이(.rep)를 여기에 끌어 놓거나",
  "Float": "띄우기",
  "Float the panel over the map": "패널을 맵 위에 띄웁니다",
  "Floating over the map": "맵 위에 떠 있음",
  "Free For All": "난전",
  "Game type {n}": "게임 유형 {n}",
  "Go to the time": "그 시간으로 이동",
  "Go to the time and place": "그 시간과 위치로 이동",
  "Greed": "탐욕",
  "Heat: all orders": "히트맵: 모든 명령",
  "Heat: attacks": "히트맵: 공격",
  "Heat: buildings": "히트맵: 건물",
  "Heat: minimap pings": "히트맵: 미니맵 핑",
  "Heat: moves": "히트맵: 이동",
  "Ladder": "래더",
  "Melee": "밀리",
  "No builds, units or research ordered.": "명령한 건물, 유닛, 연구가 없습니다.",
  "No heat map": "히트맵 없음",
  "Not a replay": "리플레이가 아닙니다",
  "One on One": "일대일",
  "Open Replay…": "리플레이 열기…",
  "Open the replay's map": "리플레이의 맵 열기",
  "Ordered {n} times": "{n}번 명령함",
  "Panel": "패널",
  "Pause": "일시 정지",
  "Play": "재생",
  "Playback speed": "재생 속도",
  "Protoss": "프로토스",
  "Put the panel in the right dock, beside the map": "패널을 맵 옆 오른쪽 도크에 놓습니다",
  "Random": "무작위",
  "Recent orders": "최근 명령",
  "Replay map": "리플레이 맵",
  "Show": "표시",
  "Show SCVs, Drones and Probes": "SCV, 드론, 프로브 표시",
  "Show this player on the map": "이 플레이어를 맵에 표시",
  "Slaughter": "학살",
  "Sudden Death": "서든 데스",
  "Team Capture the Flag": "팀 깃발 뺏기",
  "Team Free For All": "팀 난전",
  "Team Melee": "팀 밀리",
  "Terran": "테란",
  "The file ends in the middle of a section.": "파일이 섹션 중간에서 끝납니다.",
  "The map in front is not the one this game was played on.": "앞에 열린 맵은 이 게임을 한 맵이 아닙니다.",
  "The replay's header is too short.": "리플레이의 헤더가 너무 짧습니다.",
  "This is not a StarCraft replay.": "StarCraft 리플레이가 아닙니다.",
  "Top vs Bottom": "탑 vs 바텀",
  "Use Map Settings": "유즈맵 세팅",
  "Where units were sent in the last 8 seconds": "지난 8초 동안 유닛을 보낸 곳",
  "Whole game": "게임 전체",
  "Workers": "일꾼",
  "Zerg": "저그",
  "before 1.18": "1.18 이전",
  "left {time}": "{time}에 나감",
  "{n, plural, one {# command of a kind Aftermath does not know was skipped.} other {# commands of a kind Aftermath does not know were skipped.}}": "Aftermath가 모르는 종류의 명령 {n}개를 건너뛰었습니다.",
  "{n} APM": "{n} APM",
};
